set(CMAKE_SYSTEM_NAME Generic-ELF)
set(CMAKE_SYSTEM_PROCESSOR ARM)

set(TOOLCHAIN_TRIPLE arm-none-eabi)
find_program(CLANG_PATH clang NO_CACHE)

if (NOT CLANG_PATH)
    message(FATAL_ERROR "Clang toolchain not found")
endif ()

find_program(CLANGPP_PATH clang++ NO_CACHE)

get_filename_component(ARM_TOOLCHAIN_DIR ${CLANG_PATH} DIRECTORY)
# Without that flag CMake is not able to pass test compilation check
if (${CMAKE_VERSION} VERSION_EQUAL "3.6.0" OR ${CMAKE_VERSION} VERSION_GREATER "3.6")
    set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
else ()
    set(CMAKE_EXE_LINKER_FLAGS_INIT "--specs=nosys.specs")
endif ()

set(CMAKE_C_COMPILER ${CLANG_PATH})
set(CMAKE_ASM_COMPILER ${CMAKE_C_COMPILER})
set(CMAKE_CXX_COMPILER ${CLANGPP_PATH})
set(CMAKE_C++_LINK_EXECUTABLE ${CLANGPP_PATH})
set(CMAKE_AR ${ARM_TOOLCHAIN_DIR}/llvm-ar)
set(CMAKE_RANLIB ${ARM_TOOLCHAIN_DIR}/llvm-ranlib)

# Clang target flag
set(CLANG_TARGET_FLAG "--target=${TOOLCHAIN_TRIPLE}")

# Default C compiler flags
set(CMAKE_C_FLAGS_INIT "${CLANG_TARGET_FLAG} -ffreestanding -nostdlib -fno-builtin")
set(CMAKE_C_FLAGS_DEBUG_INIT "-g3 -Og")
set(CMAKE_C_FLAGS_DEBUG "${CMAKE_C_FLAGS_DEBUG_INIT}" CACHE STRING "" FORCE)
set(CMAKE_C_FLAGS_RELEASE_INIT "-O3")
set(CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE_INIT}" CACHE STRING "" FORCE)
set(CMAKE_C_FLAGS_MINSIZEREL_INIT "-Oz")
set(CMAKE_C_FLAGS_MINSIZEREL "${CMAKE_C_FLAGS_MINSIZEREL_INIT}" CACHE STRING "" FORCE)
set(CMAKE_C_FLAGS_RELWITHDEBINFO_INIT "-O2 -g")
set(CMAKE_C_FLAGS_RELWITHDEBINFO "${CMAKE_C_FLAGS_RELWITHDEBINFO_INIT}" CACHE STRING "" FORCE)

# Default C++ compiler flags
set(CMAKE_CXX_FLAGS_INIT "${CMAKE_C_FLAGS_INIT} -fno-exceptions -fno-unwind-tables -fno-rtti")
set(CMAKE_CXX_FLAGS_DEBUG_INIT "-g3 -Og")
set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG_INIT}" CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS_RELEASE_INIT "-O3")
set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE_INIT}" CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS_MINSIZEREL_INIT "-Oz")
set(CMAKE_CXX_FLAGS_MINSIZEREL "${CMAKE_CXX_FLAGS_MINSIZEREL_INIT}" CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO_INIT "-O2 -g")
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "${CMAKE_CXX_FLAGS_RELWITHDEBINFO_INIT}" CACHE STRING "" FORCE)

set(CMAKE_ASM_FLAGS_INIT "${CLANG_TARGET_FLAG}")

set(CMAKE_EXE_LINKER_FLAGS_INIT "${CLANG_TARGET_FLAG} -nostartfiles -fuse-ld=lld --sysroot=${CMAKE_SYSROOT} -L${CMAKE_SYSROOT}/lib/thumb/v7-m/nofp -lc -lm")

set(CMAKE_OBJCOPY ${ARM_TOOLCHAIN_DIR}/llvm-objcopy CACHE INTERNAL "objcopy tool")
set(CMAKE_SIZE_UTIL ${ARM_TOOLCHAIN_DIR}/llvm-size CACHE INTERNAL "size tool")

set(CMAKE_SYSROOT /usr/arm-none-eabi)
set(CMAKE_FIND_ROOT_PATH ${CLANG_PATH})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
